site_name: mian's blog
site_url: https://mianwtt.github.io
site_author: xiaogao
theme:
  name: material
  custom_dir: overrides

extra_css:
  - assets/styles.css

extra_javascript:
  - assets/particles.js
  
